name: CI

on:
  push:

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt-get update && sudo apt-get install -y "libclang-14-dev"
      - uses: actions/checkout@v2
      - name: Configure
        run: |
          CC=clang-14 CXX=clang++-14 cmake -S . -B build -DCMAKE_PREFIX_PATH=/usr/lib/llvm-14
      - name: Build
        run: |
          cmake --build build
      - name: Test
        run: |
          mkdir -p build/bin
          ln -s "$(which FileCheck-14)" build/bin/FileCheck
          PATH=$PWD/build/bin:$PATH ctest --test-dir build -V
