name: CI

on:
  push:

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure
        run: |
          cmake -S . -B build -DCMAKE_PREFIX_PATH=/usr/lib/llvm-14
      - name: Build
        run: |
          cmake --build build
      - name: Test
        run: |
          ctest --test-dir build -V
